/*
 * This file is generated by jOOQ.
 */
package com.example.financialdataapp;


import com.example.financialdataapp.tables.AccountMaster;
import com.example.financialdataapp.tables.Company;
import com.example.financialdataapp.tables.DocumentMetadata;
import com.example.financialdataapp.tables.FinancialData;
import com.example.financialdataapp.tables.FinancialDocument;
import com.example.financialdataapp.tables.records.AccountMasterRecord;
import com.example.financialdataapp.tables.records.CompanyRecord;
import com.example.financialdataapp.tables.records.DocumentMetadataRecord;
import com.example.financialdataapp.tables.records.FinancialDataRecord;
import com.example.financialdataapp.tables.records.FinancialDocumentRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountMasterRecord> CONSTRAINT_4 = Internal.createUniqueKey(AccountMaster.ACCOUNT_MASTER, DSL.name("CONSTRAINT_4"), new TableField[] { AccountMaster.ACCOUNT_MASTER.ID }, true);
    public static final UniqueKey<AccountMasterRecord> CONSTRAINT_43 = Internal.createUniqueKey(AccountMaster.ACCOUNT_MASTER, DSL.name("CONSTRAINT_43"), new TableField[] { AccountMaster.ACCOUNT_MASTER.CODE }, true);
    public static final UniqueKey<CompanyRecord> CONSTRAINT_6 = Internal.createUniqueKey(Company.COMPANY, DSL.name("CONSTRAINT_6"), new TableField[] { Company.COMPANY.ID }, true);
    public static final UniqueKey<CompanyRecord> CONSTRAINT_63 = Internal.createUniqueKey(Company.COMPANY, DSL.name("CONSTRAINT_63"), new TableField[] { Company.COMPANY.EDINET_CODE }, true);
    public static final UniqueKey<CompanyRecord> CONSTRAINT_637 = Internal.createUniqueKey(Company.COMPANY, DSL.name("CONSTRAINT_637"), new TableField[] { Company.COMPANY.SECURITY_CODE }, true);
    public static final UniqueKey<CompanyRecord> CONSTRAINT_6372 = Internal.createUniqueKey(Company.COMPANY, DSL.name("CONSTRAINT_6372"), new TableField[] { Company.COMPANY.CORPORATE_NUMBER }, true);
    public static final UniqueKey<DocumentMetadataRecord> CONSTRAINT_F = Internal.createUniqueKey(DocumentMetadata.DOCUMENT_METADATA, DSL.name("CONSTRAINT_F"), new TableField[] { DocumentMetadata.DOCUMENT_METADATA.ID }, true);
    public static final UniqueKey<DocumentMetadataRecord> CONSTRAINT_FB = Internal.createUniqueKey(DocumentMetadata.DOCUMENT_METADATA, DSL.name("CONSTRAINT_FB"), new TableField[] { DocumentMetadata.DOCUMENT_METADATA.DOCUMENT_ID }, true);
    public static final UniqueKey<FinancialDataRecord> CONSTRAINT_B = Internal.createUniqueKey(FinancialData.FINANCIAL_DATA, DSL.name("CONSTRAINT_B"), new TableField[] { FinancialData.FINANCIAL_DATA.ID }, true);
    public static final UniqueKey<FinancialDocumentRecord> CONSTRAINT_7 = Internal.createUniqueKey(FinancialDocument.FINANCIAL_DOCUMENT, DSL.name("CONSTRAINT_7"), new TableField[] { FinancialDocument.FINANCIAL_DOCUMENT.ID }, true);
    public static final UniqueKey<FinancialDocumentRecord> CONSTRAINT_76 = Internal.createUniqueKey(FinancialDocument.FINANCIAL_DOCUMENT, DSL.name("CONSTRAINT_76"), new TableField[] { FinancialDocument.FINANCIAL_DOCUMENT.DOCUMENT_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FinancialDataRecord, FinancialDocumentRecord> CONSTRAINT_BD = Internal.createForeignKey(FinancialData.FINANCIAL_DATA, DSL.name("CONSTRAINT_BD"), new TableField[] { FinancialData.FINANCIAL_DATA.FINANCIAL_DOCUMENT_ID }, Keys.CONSTRAINT_7, new TableField[] { FinancialDocument.FINANCIAL_DOCUMENT.ID }, true);
    public static final ForeignKey<FinancialDocumentRecord, CompanyRecord> CONSTRAINT_764 = Internal.createForeignKey(FinancialDocument.FINANCIAL_DOCUMENT, DSL.name("CONSTRAINT_764"), new TableField[] { FinancialDocument.FINANCIAL_DOCUMENT.COMPANY_ID }, Keys.CONSTRAINT_6, new TableField[] { Company.COMPANY.ID }, true);
}
