/*
 * This file is generated by jOOQ.
 */
package com.example.financialdataapp;


import com.example.financialdataapp.tables.AccountMaster;
import com.example.financialdataapp.tables.Company;
import com.example.financialdataapp.tables.DocumentMetadata;
import com.example.financialdataapp.tables.FinancialData;
import com.example.financialdataapp.tables.FinancialDocument;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ACCOUNT_MASTER</code>.
     */
    public final AccountMaster ACCOUNT_MASTER = AccountMaster.ACCOUNT_MASTER;

    /**
     * The table <code>PUBLIC.COMPANY</code>.
     */
    public final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>PUBLIC.DOCUMENT_METADATA</code>.
     */
    public final DocumentMetadata DOCUMENT_METADATA = DocumentMetadata.DOCUMENT_METADATA;

    /**
     * The table <code>PUBLIC.FINANCIAL_DATA</code>.
     */
    public final FinancialData FINANCIAL_DATA = FinancialData.FINANCIAL_DATA;

    /**
     * The table <code>PUBLIC.FINANCIAL_DOCUMENT</code>.
     */
    public final FinancialDocument FINANCIAL_DOCUMENT = FinancialDocument.FINANCIAL_DOCUMENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccountMaster.ACCOUNT_MASTER,
            Company.COMPANY,
            DocumentMetadata.DOCUMENT_METADATA,
            FinancialData.FINANCIAL_DATA,
            FinancialDocument.FINANCIAL_DOCUMENT
        );
    }
}
