/*
 * This file is generated by jOOQ.
 */
package com.example.financialdataapp;


import com.example.financialdataapp.tables.AccountMaster;
import com.example.financialdataapp.tables.Company;
import com.example.financialdataapp.tables.DocumentMetadata;
import com.example.financialdataapp.tables.FinancialData;
import com.example.financialdataapp.tables.FinancialDocument;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT_MASTER</code>.
     */
    public static final AccountMaster ACCOUNT_MASTER = AccountMaster.ACCOUNT_MASTER;

    /**
     * The table <code>PUBLIC.COMPANY</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>PUBLIC.DOCUMENT_METADATA</code>.
     */
    public static final DocumentMetadata DOCUMENT_METADATA = DocumentMetadata.DOCUMENT_METADATA;

    /**
     * The table <code>PUBLIC.FINANCIAL_DATA</code>.
     */
    public static final FinancialData FINANCIAL_DATA = FinancialData.FINANCIAL_DATA;

    /**
     * The table <code>PUBLIC.FINANCIAL_DOCUMENT</code>.
     */
    public static final FinancialDocument FINANCIAL_DOCUMENT = FinancialDocument.FINANCIAL_DOCUMENT;
}
