/*
 * This file is generated by jOOQ.
 */
package com.example.financialdataapp.tables.records;


import com.example.financialdataapp.tables.AccountMaster;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountMasterRecord extends UpdatableRecordImpl<AccountMasterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.ACCOUNT_MASTER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ACCOUNT_MASTER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ACCOUNT_MASTER.CODE</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ACCOUNT_MASTER.CODE</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ACCOUNT_MASTER.NAME_JP</code>.
     */
    public void setNameJp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ACCOUNT_MASTER.NAME_JP</code>.
     */
    public String getNameJp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ACCOUNT_MASTER.NAME_EN</code>.
     */
    public void setNameEn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ACCOUNT_MASTER.NAME_EN</code>.
     */
    public String getNameEn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ACCOUNT_MASTER.BALANCE</code>.
     */
    public void setBalance(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ACCOUNT_MASTER.BALANCE</code>.
     */
    public String getBalance() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountMasterRecord
     */
    public AccountMasterRecord() {
        super(AccountMaster.ACCOUNT_MASTER);
    }

    /**
     * Create a detached, initialised AccountMasterRecord
     */
    public AccountMasterRecord(Long id, String code, String nameJp, String nameEn, String balance) {
        super(AccountMaster.ACCOUNT_MASTER);

        setId(id);
        setCode(code);
        setNameJp(nameJp);
        setNameEn(nameEn);
        setBalance(balance);
        resetChangedOnNotNull();
    }
}
