/*
 * This file is generated by jOOQ.
 */
package com.example.financialdataapp.tables.records;


import com.example.financialdataapp.tables.FinancialDocument;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FinancialDocumentRecord extends UpdatableRecordImpl<FinancialDocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DOCUMENT.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DOCUMENT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DOCUMENT.DOCUMENT_ID</code>.
     */
    public void setDocumentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DOCUMENT.DOCUMENT_ID</code>.
     */
    public String getDocumentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DOCUMENT.EDINET_CODE</code>.
     */
    public void setEdinetCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DOCUMENT.EDINET_CODE</code>.
     */
    public String getEdinetCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DOCUMENT.DOCUMENT_TYPE</code>.
     */
    public void setDocumentType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DOCUMENT.DOCUMENT_TYPE</code>.
     */
    public String getDocumentType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DOCUMENT.FISCAL_YEAR_END_DATE</code>.
     */
    public void setFiscalYearEndDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DOCUMENT.FISCAL_YEAR_END_DATE</code>.
     */
    public LocalDate getFiscalYearEndDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DOCUMENT.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DOCUMENT.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DOCUMENT.COMPANY_ID</code>.
     */
    public void setCompanyId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DOCUMENT.COMPANY_ID</code>.
     */
    public Long getCompanyId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FinancialDocumentRecord
     */
    public FinancialDocumentRecord() {
        super(FinancialDocument.FINANCIAL_DOCUMENT);
    }

    /**
     * Create a detached, initialised FinancialDocumentRecord
     */
    public FinancialDocumentRecord(Long id, String documentId, String edinetCode, String documentType, LocalDate fiscalYearEndDate, String currency, Long companyId) {
        super(FinancialDocument.FINANCIAL_DOCUMENT);

        setId(id);
        setDocumentId(documentId);
        setEdinetCode(edinetCode);
        setDocumentType(documentType);
        setFiscalYearEndDate(fiscalYearEndDate);
        setCurrency(currency);
        setCompanyId(companyId);
        resetChangedOnNotNull();
    }
}
