/*
 * This file is generated by jOOQ.
 */
package com.example.financialdataapp.tables.records;


import com.example.financialdataapp.tables.FinancialData;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FinancialDataRecord extends UpdatableRecordImpl<FinancialDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.FINANCIAL_DOCUMENT_ID</code>.
     */
    public void setFinancialDocumentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.FINANCIAL_DOCUMENT_ID</code>.
     */
    public Long getFinancialDocumentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.ACCOUNT_ID</code>.
     */
    public void setAccountId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.ACCOUNT_ID</code>.
     */
    public String getAccountId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.PERIOD_TYPE</code>.
     */
    public void setPeriodType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.PERIOD_TYPE</code>.
     */
    public String getPeriodType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.PERIOD_UNIT</code>.
     */
    public void setPeriodUnit(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.PERIOD_UNIT</code>.
     */
    public String getPeriodUnit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.CONSOLIDATED_TYPE</code>.
     */
    public void setConsolidatedType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.CONSOLIDATED_TYPE</code>.
     */
    public String getConsolidatedType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.CONTEXT_REF</code>.
     */
    public void setContextRef(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.CONTEXT_REF</code>.
     */
    public String getContextRef() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.DISPLAY_SCALE</code>.
     */
    public void setDisplayScale(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.DISPLAY_SCALE</code>.
     */
    public String getDisplayScale() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.FINANCIAL_DATA.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.FINANCIAL_DATA.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FinancialDataRecord
     */
    public FinancialDataRecord() {
        super(FinancialData.FINANCIAL_DATA);
    }

    /**
     * Create a detached, initialised FinancialDataRecord
     */
    public FinancialDataRecord(Long id, Long financialDocumentId, String accountId, String periodType, String periodUnit, String consolidatedType, String contextRef, BigDecimal amount, String displayScale, String currency) {
        super(FinancialData.FINANCIAL_DATA);

        setId(id);
        setFinancialDocumentId(financialDocumentId);
        setAccountId(accountId);
        setPeriodType(periodType);
        setPeriodUnit(periodUnit);
        setConsolidatedType(consolidatedType);
        setContextRef(contextRef);
        setAmount(amount);
        setDisplayScale(displayScale);
        setCurrency(currency);
        resetChangedOnNotNull();
    }
}
