ALTER TABLE document_metadata
  ADD COLUMN created_at TIMESTAMP NOT NULL,
  ADD COLUMN updated_at TIMESTAMP NOT NULL,
  ADD COLUMN created_by VARCHAR(255),
  ADD COLUMN updated_by VARCHAR(255);

ALTER TABLE financial_document
  ADD COLUMN created_at TIMESTAMP NOT NULL,
  ADD COLUMN updated_at TIMESTAMP NOT NULL,
  ADD COLUMN created_by VARCHAR(255),
  ADD COLUMN updated_by VARCHAR(255);